<?php

class NotifyScheduleTaskConstants
{
    const EDITOR_CHEFE_USER_GROUP = 3;
    const EDITOR_ASSOCIADO_USER_GROUP = 5;
    const AUTOR_USER_GROUP = 14;

    const STATUS_AVA_EDITOR_ASSOCIADO = 'ava_com_editor_associado';
    const STATUS_AVA_AGUARDANDO_AUTOR = 'ava_aguardando_autor';

    const PRIMEIRO_AVISO_ASSOCIADO_EMAIL_KEY = 'AVISO_INATIVIDADE_EDITOR_ASSOCIADO_PRIMEIRO';
    const SEGUNDO_AVISO_ASSOCIADO_EMAIL_KEY = 'AVISO_INATIVIDADE_EDITOR_ASSOCIADO_SEGUNDO';
    const AVISO_EDITOR_CHEFE_MAIL_KEY = 'AVISO_INATIVIDADE_EDITOR_CHEFE';
    const AVISO_AUTOR_EMAIL_KEY = 'AVISO_INATIVIDADE_AUTOR';

    const NOTIFICATION_STATUS_CSP_PRIMEIRO_AVISO = '1';
    const NOTIFICATION_STATUS_CSP_SEGUNDO_AVISO = '2';
}
